config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'

  resources :items, only: [:index, :show]

  get '/mypage' => 'public#show'
  get '/mypage' => 'public#edit'
  patch '/mypage' => 'public#update'
  get '/mypage/unsubscribe' => 'public#unsubscribe', as: 'unsubscribe'
  patch '/mypage/withdraw' => 'public#withdraw', as: 'withdraw'

  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]

  post '/orders/confirmation' => 'orders#confirmation'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only: [:index, :show, :new, :create]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  get "/items/genre_search/:id" => "items#genre_search", as: 'items_genre_search'

  end

  namespace :admin do
  root to: "homes#top"

  resources :items, except: [:destroy]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :customers, only: [:index, :show, :edit, :update]

  resources :orders, only: [:show, :update]

  resources :order_details, only: [:update]

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders
  has_many :cart_items
  has_many :addresses
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def edit
  end
  
  def create
  end
  
  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(admin_item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(admin_item_params)
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def admin_item_params
    params.require(:item).permit(:name, :image, :genre_id, :description, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end
  
  def update
  end 
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h1>Admin::Genres#edit</h1>
<p>Find me in app/views/admin/genres/edit.html.erb</p>

app/views/admin/genres/index.html.erb
<h1>Admin::Genres#index</h1>
<p>Find me in app/views/admin/genres/index.html.erb</p>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
  <p>商品画像</p>
  <%= f.file_field :image, accept: "image/*" %>
  <p>商品名</p>
  <%= f.text_field :name %>
  <p>商品説明</p>
  <%= f.text_area :description %>
  <p>ジャンル</p>
  <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "--選択してください--"} %>
  <p>税抜き価格</p>
  <%= f.number_field :price %>
  <%= f.submit '変更を保存', class: "btn btn-success" %>
<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<% @items.each do |item| %>
  <%= item.id %>
  <%= link_to admin_item_path(item.id) do %>
    <%= item.name %>
  <% end %>
  <%= item.genre.name %>
  <%= item.price %>
<% end %>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
    <p>商品画像</p>
    <%= f.file_field :image, accept: "image/*" %>
    <P>商品名</P>
    <%= f,text_field :name %>
    <P>商品説明</P>
    <%= f.text_field :description %>
    <P>ジャンル</P>
    <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "--選択してください--"} %>
    <P>税抜価格</P>
    <%= f.number_field :price %>
    <div>
        <%= f.submit '新規登録', class: "btn btn-success" %>
    </div>

app/views/admin/items/show.html.erb
<h3>商品詳細</h3>
<%= image_tag @item.get_image(300, 300) %>

<p>商品名</p>
<div><%= @item.name %></div>

<p>商品説明</p>
<div><%= @item.description %></div>

<P>ジャンル</P>
<div><%= @item.genre.name %></div>

<div>
    <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
</div>

app/views/admin/orders/show.html.erb
<h1>Admin::Orders#show</h1>
<p>Find me in app/views/admin/orders/show.html.erb</p>