config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'

  resources :items, only: [:index, :show]

  get '/mypage' => 'public#show'
  get '/mypage' => 'public#edit'
  patch '/mypage' => 'public#update'
  get '/mypage/unsubscribe' => 'public#unsubscribe', as: 'unsubscribe'
  patch '/mypage/withdraw' => 'public#withdraw', as: 'withdraw'

  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]

  post '/orders/confirmation' => 'orders#confirmation'
  get '/orders/complete' => 'orders#complete'
  resources :orders, only: [:index, :show, :new, :create]

  resources :addresses, only: [:index, :create, :edit, :update, :destroy]

  get "/items/genre_search/:id" => "items#genre_search", as: 'items_genre_search'

  end

  namespace :admin do
  root to: "homes#top"

  resources :items, except: [:destroy]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :customers, only: [:index, :show, :edit, :update]

  resources :orders, only: [:show, :update]

  resources :order_details, only: [:update]

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders
  has_many :cart_items
  has_many :addresses
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def edit
  end
  
  def create
  end
  
  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(admin_item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(admin_item_params)
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def admin_item_params
    params.require(:item).permit(:name, :image, :genre_id, :description, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<% if admin_signed_in? %>
  <% if request.fullpath.include? "/admin" %>
    <li class="nav-item">
      <%= link_to "商品一覧", admin_items_path %>
    </li>
    <li class="nav-item">
      <%= link_to "会員一覧", admin_customers_path %>
    </li>
    <li class="nav-item">
      <%= link_to "注文履歴一覧", admin_root_path %>
    </li>
    <li class="nav-item">
      <%= link_to "ジャンル一覧", admin_genres_path %>
    </li>
    <li class="nav-item">
      <%= link_to "ログアウト", destoroy_admin_session_path, method: :delete %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to "About", about_path %>
    </li>
    <li class="nav-item">
      <%= link_to "商品一覧", items_path %>
    </li>
    <li class="nav-item">
      <%= link_to "新規登録", new_customer_registration_path %>
    </li>
    <li class="nav-item">
      <%= link_to "ログイン", new_customer_session_path %>
    </li>
  <% end %>
<% elsif customer_signed_in? %>
  <li class="nav-item">
    <%= link_to "商品一覧", items_path %>
  </li>
  <li class="nav-item">
    <%= link_to "カート", cart_items_path %>
  </li>
  <li class="nav-item">
    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "About", about_path %>
  </li>
  <li class="nav-item">
    <%= link_to "商品一覧", items_path %>
  </li>
  <li>
    <%= link_to "新規登録", new_customer_registration_path %>
  </li>
  <li class="nav-item">
    <%= link_to "ログイン", new_customer_session_path %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstFace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
    <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>